# Generated by Django 5.1.4 on 2024-12-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_phonebook_delete_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('pswd', models.TextField()),
            ],
        ),
    ]
