# Generated by Django 5.1.4 on 2024-12-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_delete_cuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
